### ISSUE TITLE
Consider deprecating this driver

### ISSUE THREAD

**Issue by stof** [minkphp/MinkWUnitDriver#10]
This driver is not tested (see #9 and #4). It is duplicating the code of https://github.com/weavora/wunit (which also looks unmaintained) which does not care at all about the composer era (see https://github.com/weavora/wunit/issues/12)

I suggest marking this driver as deprecated (and unmaintained), acknowledging the fact that we haven't worked on it since years. If anyone is using the driver and wants to bring it uptodate, we can still make them a driver maintainer and undeprecate the driver (once properly tested and green.

/cc @minkphp/core-team @minkphp/wunit

**Comment by patrickdreyer** [comment]
I agree.

Am 26. Februar 2016 13:43:32 MEZ, schrieb Christophe Coevoet notifications@github.com:

> This driver is not tested (see #9 and #4). It is duplicating the code
> of https://github.com/weavora/wunit (which also looks unmaintained)
> which does not care at all about the composer era (see
> https://github.com/weavora/wunit/issues/12)
> 
> I suggest marking this driver as deprecated (and unmaintained),
> acknowledging the fact that we haven't worked on it since years. If
> anyone is using the driver and wants to bring it uptodate, we can still
> make them a driver maintainer and undeprecate the driver (once properly
> tested and green.
> 
> /cc @minkphp/core-team @minkphp/wunit 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/minkphp/MinkWUnitDriver/issues/10

## 

Sent from my mobile.
Please excuse the brevity.

**Comment by stof** [comment]
OK, this is done in the repo description and on packagist.
