### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by aik099** [minkphp/MinkWUnitDriver#4]
Right now there are no unit tests or Travis CI integration, which makes it pretty hard to safely make changes to the driver code.

@patrickdreyer can you please add tests (I'm guessing this will be similar to ones, done in MinkGoutteDriver, where MinkBrowserKitDriver tests are executed).

**Comment by aik099** [comment]
I've tried to add following test:

``` php
class WUnitDriverTest extends HeadlessDriverTest
{
    protected static function getDriver()
    {
        \Yii::setApplication(\WUnit\WUnit::createWebApplication());

        return new WUnitDriver();
    }
}
```

This didn't work. I've figured out, that I need some kind of Yii application that would represent website with web fixtures. Also I've added dependency to Yii framework in composer.json, since otherwise I've just got missing classes error.

**Comment by patrickdreyer** [comment]
The only unit test would be for testing the constructor.
Everything else would test either the base class or the underlying Client or HttpKernelInterface implementation, YiiKernel in this case.
Or am I missing something here

**Comment by aik099** [comment]
Same as MinkGoutteDriver. We're just testing, that used Client class really does fetch pages and do MinkBrowserKitDriver operations on them.

Besides, does it curl pages as Goutte driver or not?

**Comment by patrickdreyer** [comment]
No, it's one step further to having a headless browser emulator, as it _DIRECTLY_ calls the Yii application.
As you can see, _WUnit::createClient()_ initializes the _HttpKernel\Client_ instance with the _HttpKernelInterface_ implementation _YiiKernel_.
_YiiKernel_ first fetches the Yii application _\Yii::app()_ and calls DIRECTLY it's _processRequest()_ method.
You may do rich and non rich UI testing in one Behat run.
Simply tag your rich UI test scenarios with _@javascript_ or _@mink:selenium2_ as explained on http://docs.behat.org/cookbook/behat_and_mink.html#test-in-browser-selenium2-session

**Comment by patrickdreyer** [comment]
Yii framework should only be a dependency for testing, otherwise we'll sure have conflicts. This as most users probably still do _NOT_ install Yii the composer way (like myself), thus they end up with a directory structure like:

```
my-application (Yii installation goes here)
-+------------
 +-- framework
 +-- protected
 |   -+-------
 |    +-- ...
 |    +-- tests
 |    |   -+---
 |    |    +-- bin
 |    |    +-- ...
 |    |    +-- vendor (here go the composer downloads)
 |    |    +-- bootstrap.php
 |    |    +-- composer.json
 |    |    +-- ...
 |    +-- ...
 +-- themes
 +-- .htaccess
 +-- index.php
```

Having Yii as MinkWUnitDriver dependency by default would end up in having Yii present twice.

**Comment by aik099** [comment]
As dev dependency only of course. If you're willing to add missing tests, then you're welcome.

**Comment by patrickdreyer** [comment]
Looking at https://github.com/weavora/wunit guys, they already have quite some tests.
Let me get in contact with those guys.
The final goal is:
- make weavora/wunit composer aware
- remove the whole WUnit stuff from this repository
- depend this repository from weavora/wunit

This way the testing is covered by the weavora/wunit repo.
However, we for sure don't wanna maintain a copy of them.

**Comment by stof** [comment]
See https://github.com/weavora/wunit/issues/12 for the first point.

However, this package seems quite unmaintained. Except for a few readme changes, the last update was 2 years ago

**Comment by patrickdreyer** [comment]
You are right, and I just saw that I already placed an Issue there about getting the package composer ready - no answer so far.
Probably better to start a fork under Behat/WUnit and then apply the steps in my last comment.

**Comment by stof** [comment]
@patrickdreyer I don't think it makes sense to maintain WUnit in its own repo in the Behat organization. It is something specific to Yii, which is not used by any of the core team AFAIK (I might be wrong here though). Either a maintained version of WUnit with proper composer support appears in another orga (or on a personal account for that matter), or I suggest keeping the code inside the driver repo itself.

**Comment by patrickdreyer** [comment]
Thanks for your thoughts @stof.
This leads me to:
- place an issue at weavora/wunit what we are up to - just in case
- Copy&Paste the tests from weavora/wunit
- Check if Yii dependency is required for testing; most probably yes as the fixtures include a whole bunch of Yii related stuff
- adapt the tests due to refactored YiiRequest
- get the tests running
- place an issue in weavora/wunit that we are running
- release version 1.0.0

**Comment by stof** [comment]
@patrickdreyer do you have any news about the composer support in WUnit itself to relu on their package rather than duplicating it ?

**Comment by stof** [comment]
I created a separate issue to discuss about running the driver testsuite as this discussion is talking about the tests for WUnit itself: https://github.com/minkphp/MinkWUnitDriver/issues/9
